### ISSUE TITLE
question: how to override mapper parameters?

### ISSUE THREAD

**Issue by astewart-twist** [karel-brinda/rnftools#51]
Is it possible somehow to pass parameters to the mapping algorithm, similar to how args can be passed to different read simulators?

For example:

```
alignments = [
    smbl.prog.BwaMem(
      fasta=reference,
      fastq_1=reads,
      bam="BWA-MEM.bam",
      params="-t 4 -E 0,1",
    ),
  ]
```

**Comment by karel-brinda** [comment]
Hello, it is not currently possible. If you need this feature, I can add it or you can make a pull request for it. However, I currently prefer to have separate Snakefiles and directories for read simulation, mapping, and evaluation. See, e.g., https://github.com/karel-brinda/dymas/tree/ococo/experiments/exp1.01__Borrelia__0.07-baq.

**Comment by karel-brinda** [comment]
Since the SMBL dependency has been removed from RNFtools, I am closing this issue.
