### ISSUE TITLE
Mark random reads that are mixed in by simulator in LRN (genome ID)

### ISSUE THREAD

**Issue by sibyllewohlgemuth** [karel-brinda/rnftools#62]
If random reads are generated by the read simulator (eg. CuReSim -r ) and these reads are marked in the read name of the original simulator, it would be nice if they would have a different genome ID in the RNF name.

**Comment by karel-brinda** [comment]
Could you provide a specific Snakefile that you are using in this case? CuReSim random reads are switched off in RNFtools, see [this line](https://github.com/karel-brinda/rnftools/blob/6acbb310ea3fc538b6e324a3285823f461d42ee2/rnftools/mishmash/CuReSim.py#L110). If you want to simulate contamination, it should be added through a separate source.

I could add a random mode option to `rnftools.mishmash.CuReSim`. Then your Snakefile could look like this:

```python
# non-random reads
rnftools.mishmash.CuReSim(
       fasta=fa,
       number_of_read_tuples=10000,
       read_length_1=100,
       read_length_2=0,
)
# random reads
rnftools.mishmash.CuReSim(
       fasta=fa,
       number_of_read_tuples=2000,
       read_length_1=100,
       read_length_2=0,
       random=True,
)
```

**Comment by sibyllewohlgemuth** [comment]
Yes, exactly I wanted to mix in random contamination and i thougt I could do it with
```Python
rnftools.mishmash.CuReSim(
	fasta=random,
        number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
	other_params='-r 1000'
)
```

To have a random mode option would be useful! Then I can add the contamination through a separate source and it would have different genome ID.

**Comment by karel-brinda** [comment]
@sibyllewohlgemuth I added this feature, see the `curesim_random` branch. Could you check if it does what you expect? Thanks.

Example:
```python
rnftools.mishmash.CuReSim(
	fasta=fa,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
)

rnftools.mishmash.CuReSim(
	fasta=fa,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
	random_reads=True,
)
```

**Comment by karel-brinda** [comment]
You can use the following command to install RNFtools from that branch:
```
pip install --upgrade https://github.com/karel-brinda/rnftools/archive/curesim_random.zip
```

**Comment by sibyllewohlgemuth** [comment]
Hi Karel,
I tried the random mode and it does what I expected!
Thank you!
