### ISSUE TITLE
RNF spec inaccessible

### ISSUE THREAD

**Issue by rsuchecki** [karel-brinda/rnftools#76]
Thank you for creating and sharing RNFtools Karel, 

Basics of RNF format are pretty clearly stated in your paper, but I am not able to access the RNF spec at https://karel-brinda.github.io/rnf-spec which gives a 404

Rad

**Comment by karel-brinda** [comment]
Sorry for that. The spec was migrated to the RNFtools GH account, but GH doesn't create redirects for the webpages. The new address is the following:
https://rnftools.github.io/rnf-spec/RNF.pdf

**Comment by rsuchecki** [comment]
Great, many thanks!
